# Generated by Django 3.1.8 on 2021-04-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='resume.Skill'),
        ),
    ]
